function [f_est G_est] = Unitary_ESPRIT(x,M,K)
X = buffer(x,M,M-1,'nodelay');
L = size(X,2);
Z = [X IEM(M)*conj(X)*IEM(L)];
QM = UniMat(M);
Q2L = UniMat(L*2);
Zc = real(QM'*Z*Q2L);
[U D V] = svd(Zc);
Uz = U(:,1:K);
Us = QM*Uz;
U1 = Us(1:end-1,:);
U2 = Us(2:end,:);
Psi = inv(U1'*U1)*U1'*U2;
[V,D] = eig(Psi);
d = diag(D);
f_est = angle(d)/pi;
Phi = D;
A_est = exp(1i*f_est*pi*(0:length(x)-1)).';
G_est = abs(inv(A_est'*A_est)*A_est'*x.');